### ISSUE TITLE
Memory Leak in FloatMappingNeuron

### ISSUE THREAD

**Issue by LordTocs** [johnlime/UnitNeurons#2]
Hello, I found your code while scrolling through reddit. It's a nice project you have going.

I believe you have a memory leak in `FloatMappingNeuron` via `assign_neighbors()`

In the `kohonen_som` example, you new up an array on line 70, but then it's never deleted.

You could try storing neighbors in a `std::unique_ptr<FloatMappingNeuron *[]>` or instead of a raw array use a `std::vector<FloatMappingNeuron*>`.

I suspect you might have a few more leaks around as well with some `new`s missing their `delete`.

Either way, cool project and keep up the good work.

**Comment by johnlime** [comment]
@LordTocs
Thank you so so much for taking a look at my code and providing your insight.

Please correct me if I am wrong, but the aforementioned L70's `FloatMappingNeuron** tmp` is a pointer to the array that contains memory addresses of `FloatMappingNeuron` instances and the `assign_neighbors()` function stores such pointer into the instance of the current `FloatMappingNeuron`; therefore, freeing up the original memory address to `tmp` (using `delete` afterwards) would allow another set of data to utilize that address, rendering the `assign_neurons()` meaningless. I state this, because I ran into that issue while I was writing the code for that class and method, and I had to add the `new` during declaration.

**Comment by LordTocs** [comment]
Yeah, Sorry I should have been more clear.

When you call `assign_neurons()` you are passing the memory off to the `FloatMappingNeuron`, but `FloatMappingNeuron` doesn't have a destructor. So when your `FloatMappingNeuron` is destroyed the memory you handed off with `assign_neighbors()` is never deleted causing the leak.

If you use a `std::unique_ptr<FloatMappingNeuron *[]>`, when FloatMappingNeuron is destroyed it'll call `std:;unique_ptr<>`'s destructor which will delete the memory you handed off.

Alternatively, you could store a `std::vector<FloatMappingNeuron*>` in `FloatMappingNeuron`, since it manages it's memory internally it'll clean up it's memory on destruct as well.

So you would be correct using `delete` on `tmp` after `assign_neighbors()` would free the memory you just handed to FloatMappingNeuron up wreaking havoc in the future when it tried to use it.

Does that make sense?

**Comment by johnlime** [comment]
@LordTocs 
> So when your FloatMappingNeuron is destroyed the memory you handed off with assign_neighbors() is never deleted causing the leak.

That makes a lot of sense! 

But the thing is, `FloatMappingNeuron` doesn't really get destroyed throughout the entirety of `main()`, since the object instance is used to both training and testing. In the context of this program, would a destructor be necessary?

Also, if I were to destroy `FloatMappingNeuron`, in theory, would it be possible to manually delete the memory passed via `assign_neighbors()` and prevent such memory leaks?

Apologies for putting out so many questions, but I want to ask one more. I keep hearing about people preferring to use smart pointers in C++, but wouldn't that, how should I say this, put you further away from having full control of memory management than using raw pointers?

**Comment by LordTocs** [comment]
Hey Sorry I took so long to get back to you. Somehow being stuck at home has made me even more busy.

So while using a smart pointer does offload the actual act of freeing the memory to what is effectively a utility. I wouldn't view it as loss of full control. You still control *when* the memory gets released. So personally, I like to view it more as object lifetime management. 

Memory allocation and deallocation are time-costly operations. So a performance minded person wants to make sure the allocations and deallocations aren't happening in a way that's negatively impacting performance. You always have to pay the memory piper his time, C++ just lets you choose how and when you pay him. Smart pointers just make sure you don't forget to pay him.

Currently in your code you've forgotten to pay the proverbial piper for deallocation. Which in the sample code isn't really an issue because your stuff terminates before it's an issue. But if for instance you had a program using your `FloatMappingNeuron` to train many models one after the other inside a loop. You would be leaking memory like a sieve.

One of the big ways C++ differentiates it self from C is through RAII (Resource Acquisition Is Initialization). In the land of C you could request memory with `malloc()` and then forget to initialize it. In C++ when you ask for memory with `new` the constructor runs. So when a resource (an object) is aquired it is initialized. The part missing from this acronym is the role the destructor plays. In C land if you had some memory pointing to other memory. You could potentially free the first memory bit up and forget to free the memory it's pointing to. Leaking it into the void. So with RAII in C++, when an object is destroyed it's responsible for cleaning up any memory it owns.

So you still *control* when the memory gets released by controlling when the destructor runs. To control when the destructor runs you control the lifetime of the object. Smart pointers make this easier to control in my opinion. `std::unique_ptr` is relatively simple it just deletes what it's holding when it's destructor is run. If it goes out of scope, an exception winds up the stack, or the object it's a member of gets destroyed it'll take whatever it's pointing to with it. `std::shared_ptr` is a bit more nuanced because it's a reference counting pointer. Multiple objects can point to one thing and it'll only destroy what it's holding onto when the last pointer goes away. So if you wanted to say... batch your deletes for some non performance critical moment, you could store a list of `std::shared_ptr<>` and then clear the list out when it's time to delete.

That said smart pointers aren't just a worry free memory management get of jail free card. Picture a very large directional graph, just using `shared_ptr<>`'s to hold your connections sounds great, but you could form a cycle causing the ref counting to fail. Or if you had a sufficiently long enough graph chain, the destructors calling other nodes destructors could eventually cause a stack overflow.

**Comment by johnlime** [comment]
Thanks so much for the insightful response!
It seems that I may need to look more into smart pointers and lifetimes in C++

**Comment by johnlime** [comment]
Temporarily closing the issue since I may be moving onto another project for now. I ended up declaring destructors for each object and using `delete []` for destruction.

Alternative solution of replacing all raw pointers to smart pointers may be implemented in the future.
